# version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"   # RabbitMQ default port for messaging
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status || exit 1"]
      interval: 5s      # Check every 5 seconds
      timeout: 5s       # Wait 5 seconds for the check to complete
      retries: 5        # Try 5 times before considering it unhealthy
      start_period: 5s  # Wait 5 seconds before starting the health check

  newsub:
    build: ./AddSubmission
    depends_on:
      rabbitmq:
        condition: service_healthy   # Wait for rabbitmq to be healthy
    ports:
      - "3000:3000"   # Expose port 3000 for your microservice
    environment:
      - RABBITMQ_HOST=rabbitmq
      - queue_db_host = solverq_db
      - queue_db_port = 27017
      
  # pend_run_subs:
  #   image: pend_run_subs
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy   # Wait for rabbitmq to be healthy
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - queue_db_host = solverq_db
  #     - queue_db_port = 27017

  pendrunnew:
    build: ./pending_sub
    container_name: pendrun
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB: Pending_Running
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy   # Wait for rabbitmq to be healthy
      mysql:
        condition: service_healthy   # Wait for mysql to be healthy
    ports:
      - "5000:8080"

  finished:
    build: ./finished_sub
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB: Finished
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy   # Wait for rabbitmq to be healthy
      mysql:
        condition: service_healthy   # Wait for mysql to be healthy
    ports:
      - "5001:8080"


  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-multiple-databases.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      retries: 5
      start_period: 30s

      
  removesub:
    build: ./deleteSubmissions
    depends_on:
      rabbitmq:
        condition: service_healthy   # Wait for rabbitmq to be healthy
    ports:
      - "8000:8000"
      
  # unlock:
  #   build: ./
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy   # Wait for rabbitmq to be healthy
  #   ports:
  #     - "9000:9000"
  
  solverq:
    build: ./SolverQueue
    depends_on:
      rabbitmq:
        condition: service_healthy   # Wait for rabbitmq to be healthy
      
  solver:
    build: ./solver
    depends_on:
      rabbitmq:
        condition: service_healthy   # Wait for rabbitmq to be healthy

  lockedsub:
    build: ./locked_sub
    depends_on:
      rabbitmq:
        condition: service_healthy   # Wait for rabbitmq to be healthy
    ports:
      - "4000:4000"        
  
  solverq_db:
    image: mongo

  locked_db:
    image: mongo
    
  analytics_db:
    image: mongo
  
  # running_pending_db:
  #   image: mongo

   # Credits database Microservice
  credit-database:
    build: ./credit_database
    container_name: credits-database
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB: Credits_View
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy   # Wait for rabbitmq to be healthy
      mysql:
        condition: service_healthy   # Wait for mysql to be healthy
    ports:
      - "8001:8080"

  # Credits Transaction Microservice
  credit-transaction:
    build: ./credit_transaction
    container_name: credit-transaction
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB: Credits_Transaction
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy   # Wait for rabbitmq to be healthy
      mysql:
        condition: service_healthy   # Wait for mysql to be healthy
    ports:
      - "8002:8080"

      
  # for analytics folder
  analytics:
      build: ./analytics
      depends_on:
        rabbitmq:
          condition: service_healthy
      ports:
        - "3080:3080"


volumes:
  mysql_data:
